### ISSUE TITLE
4.x support not working

### ISSUE THREAD

**Issue by RubberDuckShobe** [DeleteSystem32/gd-flac#2]
The module from the 4.x branch doesn't work when trying to add it to Godot 4.0
Some things I've managed to find out myself are:
- ``#include "core/os/file_access.h"`` should be ``#include "core/io/file_access.h"``, the file has been moved
- It fails when trying to find the functions ``uninitialize_flac_module`` and ``initialize_flac_module``

Steps to reproduce are:
- Clone Godot's 4.0 branch
- Add the module
- Try compiling the engine

**Comment by DeleteSystem32** [comment]
Should all be working now with commit 33b7894.
